name: Security Scan

on:
  workflow_call:

    inputs:

      fortify-enabled:
        required: true
        type: boolean

      checkmarx-enabled:
        required: true
        type: boolean

      mend-enabled:
        required: true
        type: boolean
jobs:

  security-scan:

    runs-on: ubuntu-latest

    steps:

      - name: Executar Fortify
        if: inputs.fortify-enabled
        run: |
          echo "Executando Fortify"
          echo "Fortify OK"

      - name: Executar Mend
        if: inputs.mend-enabled
        run: |
          echo "Executando Mend"
          echo "Mend OK"

      - name: Executar Checkmarx
        if: inputs.checkmarx-enabled
        run: |
          echo "Executando Checkmarx"
          echo "Checkmarx OK"
