name: Validate Release

on:
  workflow_call:

    inputs:

      environment:
        required: true
        type: string

      application:
        required: true
        type: string
jobs:

  validate-config:

    runs-on: ubuntu-latest

    steps:

      - name: Mostrar parametros
        run: |
          echo "Ambiente: ${{ inputs.environment }}"
          echo "Aplicacao: ${{ inputs.application }}"
    
      - name: Validar Configuracao
        run: |
          echo "Validando release"
          echo "Configuracao OK"
